spring.application.name=backend
#segredo para token gerado no powershell
jwt.secret=Vn9m3+W6k0Yh5n2Y4M6XkJb+z0P2J5r0P0FJcP4A8w8=
# Configuracoes de upload de arquivos
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB
file.upload-dir=uploads
